# Sponsor buttons for this repository.
# TODO: Configure your funding platforms below, then delete this comment
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: username          # GitHub Sponsors (or [user1, user2] for multiple)
# patreon: username         # Patreon
# open_collective: project  # Open Collective
# ko_fi: username           # Ko-fi
# tidelift: platform/package  # Tidelift (e.g., npm/package-name)
# community_bridge: project # Community Bridge
# liberapay: username       # Liberapay
# issuehunt: username       # IssueHunt
# polar: username           # Polar
# buy_me_a_coffee: username # Buy Me a Coffee
# thanks_dev: username      # thanks.dev
# custom: ['https://example.com/donate']  # Custom URL(s)

