# https://taskfile.dev
# Install: https://taskfile.dev/installation/
#
# Usage:
#   task              # list all tasks
#   task test         # run tests
#   task check        # run all quality checks
#   task --list-all   # show all tasks including internal ones

version: "3"

silent: true

vars:
  SRC_DIR: src/
  TEST_DIR: tests/

tasks:
  # ── Default ──────────────────────────────────────────────────
  default:
    desc: List available tasks
    cmds:
      - task --list

  # ── Environment ─────────────────────────────────────────────
  shell:
    desc: Enter the Hatch dev shell
    cmds:
      - hatch shell

  env:show:
    desc: Show all Hatch environments and scripts
    cmds:
      - hatch env show

  env:reset:
    desc: Remove and recreate the default Hatch environment
    cmds:
      - hatch env remove default
      - cmd: echo "Default environment removed. It will be recreated on next hatch command."

  env:prune:
    desc: Remove ALL Hatch environments
    prompt: This will remove ALL Hatch environments. Continue?
    cmds:
      - hatch env prune

  # ── Testing ─────────────────────────────────────────────────
  test:
    desc: Run tests
    cmds:
      - hatch run test {{.CLI_ARGS}}

  test:v:
    desc: Run tests with verbose output
    cmds:
      - hatch run test -v {{.CLI_ARGS}}

  test:cov:
    desc: Run tests with coverage
    cmds:
      - hatch run test-cov {{.CLI_ARGS}}

  test:matrix:
    desc: Run tests across all Python versions (3.11–3.14)
    cmds:
      - hatch run test:run {{.CLI_ARGS}}

  test:matrix:cov:
    desc: Run tests with coverage across all Python versions
    cmds:
      - hatch run test:cov {{.CLI_ARGS}}

  # ── Linting & Formatting ───────────────────────────────────
  lint:
    desc: Check for linting issues
    cmds:
      - hatch run lint {{.CLI_ARGS}}

  lint:fix:
    desc: Auto-fix linting issues
    cmds:
      - hatch run lint-fix {{.CLI_ARGS}}

  fmt:
    desc: Apply formatting
    cmds:
      - hatch run fmt {{.CLI_ARGS}}

  fmt:check:
    desc: Check formatting without applying
    cmds:
      - hatch run fmt-check {{.CLI_ARGS}}

  # ── Type Checking ──────────────────────────────────────────
  typecheck:
    desc: Run mypy type checker
    cmds:
      - hatch run typecheck {{.CLI_ARGS}}
  # ── Security ───────────────────────────────────────────
  security:
    desc: Run bandit security linter
    cmds:
      - hatch run bandit -r src/ {{.CLI_ARGS}}
  # ── Quality Gates ──────────────────────────────────────────
  check:
    desc: Run all quality checks (lint, format, typecheck, test)
    cmds:
      - hatch run check

  # ── Building ───────────────────────────────────────────────
  build:
    desc: Build source and wheel distributions
    cmds:
      - hatch build

  clean:
    desc: Clean build artifacts
    cmds:
      - hatch clean

  # ── Pre-commit ─────────────────────────────────────────────
  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - hatch run pre-commit install

  pre-commit:run:
    desc: Run pre-commit on all files
    cmds:
      - hatch run pre-commit run --all-files

  pre-commit:update:
    desc: Update pre-commit hooks to latest versions
    cmds:
      - hatch run pre-commit autoupdate

  # ── Utility ────────────────────────────────────────────────
  clean:todo:
    desc: Archive completed TODO items
    cmds:
      - hatch run spb-clean --todo

  doctor:
    desc: Run project health check
    cmds:
      - hatch run spb-doctor

  version:
    desc: Show project version
    cmds:
      - hatch version

  info:
    desc: Show project metadata
    cmds:
      - hatch project metadata

  # ── Run ────────────────────────────────────────────────────
  run:
    desc: Run the application
    cmds:
      - hatch run spb {{.CLI_ARGS}}

  # ── Targeted Testing ───────────────────────────────────────
  test:unit:
    desc: Run unit tests only
    cmds:
      - hatch run test tests/unit {{.CLI_ARGS}}

  test:integration:
    desc: Run integration tests only
    cmds:
      - hatch run test tests/integration {{.CLI_ARGS}}

  test:lf:
    desc: Rerun only last-failed tests
    cmds:
      - hatch run test --lf {{.CLI_ARGS}}

  # ── Dependency Info ────────────────────────────────────────
  deps:tree:
    desc: Show dependency tree (requires extras)
    cmds:
      - hatch run pip install -q pipdeptree && hatch run pipdeptree

  deps:outdated:
    desc: Check for outdated dependencies
    cmds:
      - hatch run pip list --outdated

  pip:upgrade:
    desc: Upgrade pip to the latest version
    cmds:
      - hatch run python -m pip install --upgrade pip

  # ── Database ───────────────────────────────────────────────
  db:reset:
    desc: Reset the local development database
    prompt: This will DELETE all data in the dev database. Continue?
    cmds:
      - sqlite3 var/app.sqlite3 < scripts/sql/reset.sql
      - cmd: echo "Database reset complete."

  # ── Labels ────────────────────────────────────────────────
  labels:apply:
    desc: "Apply GitHub labels (usage: task labels:apply -- --set baseline [--repo OWNER/REPO] [--dry-run])"
    cmds:
      - hatch run python scripts/apply_labels.py {{.CLI_ARGS}}

  labels:dry-run:
    desc: Preview baseline labels without applying
    cmds:
      - hatch run python scripts/apply_labels.py --set baseline --dry-run

  labels:baseline:
    desc: Apply baseline labels to the current repo
    cmds:
      - hatch run python scripts/apply_labels.py --set baseline

  labels:full:
    desc: Apply extended labels to the current repo
    cmds:
      - hatch run python scripts/apply_labels.py --set extended

  # ── Deep Clean ─────────────────────────────────────────────
  clean:dev:
    desc: "Run dev cleanup utility (usage: task clean:dev -- --todo)"
    cmds:
      - hatch run spb-clean {{.CLI_ARGS}}

  clean:all:
    desc: Remove all build artifacts and caches
    cmds:
      - hatch clean
      - cmd: python -c "import shutil, pathlib; [shutil.rmtree(p) for p in pathlib.Path('.').rglob('__pycache__')]"
      - cmd: python -c "import shutil; [shutil.rmtree(d, True) for d in ['.mypy_cache', '.ruff_cache', '.pytest_cache']]"
      - cmd: echo "All caches and build artifacts removed."
