"""MkDocs hook: auto-regenerate the command reference before each build.

The command reference page (``docs/reference/commands.md``) is normally a
point-in-time snapshot generated by ``scripts/generate_command_reference.py``.
This hook runs that generator automatically during ``mkdocs build`` and
``mkdocs serve`` so the page is always up to date — no manual
regeneration step required.

How it works:
    1. Hooks into the ``on_pre_build`` event (runs once per build, before
       any pages are processed).
    2. Imports the ``_generate()`` function from
       ``scripts/generate_command_reference.py`` and calls it.
    3. Writes the result to ``docs/reference/commands.md`` only if the
       content has actually changed (avoids unnecessary file writes that
       would trigger extra live-reload cycles during ``mkdocs serve``).

This means:
    - ``mkdocs serve`` always shows current commands (live-reload picks up
      the write if content changed).
    - ``mkdocs build`` always packages fresh command data.
    - ``task docs:commands`` and ``--check`` still work for manual use and
      CI, but are no longer *required* before building docs.

Configuration (optional ``extra`` key in ``mkdocs.yml``)::

    extra:
      generate_commands: false   # Set to false to disable auto-generation

Reference:
    https://www.mkdocs.org/user-guide/configuration/#hooks
"""

from __future__ import annotations

import importlib.util
import logging
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mkdocs.config.defaults import MkDocsConfig

# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------

HOOK_VERSION = "1.2.0"

__all__ = ["on_pre_build"]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

log = logging.getLogger("mkdocs.hooks.generate_commands")

# Resolve paths relative to this hook file → repo root
_HOOK_DIR = Path(__file__).resolve().parent
_ROOT = _HOOK_DIR.parent
_GENERATOR_SCRIPT = _ROOT / "scripts" / "generate_command_reference.py"
# TODO (template users): If you rename docs/reference/commands.md or change
#   the output path in generate_command_reference.py, update _OUTPUT to match.
_OUTPUT = _ROOT / "docs" / "reference" / "commands.md"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


# Cache the loaded generator module to avoid re-importing on
# successive builds (e.g. during mkdocs serve with live-reload).
_cached_generator: object | None = None


def _load_generator() -> object:
    """Dynamically import generate_command_reference.py as a module.

    We import dynamically rather than with a normal ``import`` because
    ``scripts/`` is not a package on ``sys.path`` — and we don't want
    to pollute ``sys.path`` permanently.

    .. warning::
        The temporary ``sys.path`` mutation is **not thread-safe**.  This
        is acceptable for MkDocs hooks (single-threaded build), but do
        not call from multi-threaded contexts.
    """
    global _cached_generator
    if _cached_generator is not None:
        return _cached_generator

    spec = importlib.util.spec_from_file_location(
        "generate_command_reference",
        str(_GENERATOR_SCRIPT),
    )
    if spec is None or spec.loader is None:
        msg = f"Cannot load {_GENERATOR_SCRIPT}"
        raise ImportError(msg)
    module = importlib.util.module_from_spec(spec)
    # Temporarily add scripts/ to sys.path so the generator can import
    # its sibling modules (e.g. _progress) if needed in the future.
    scripts_dir = str(_GENERATOR_SCRIPT.parent)
    added = False
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
        added = True
    try:
        spec.loader.exec_module(module)
    finally:
        if added:
            sys.path.remove(scripts_dir)

    _cached_generator = module
    return module


# ---------------------------------------------------------------------------
# MkDocs event handler
# ---------------------------------------------------------------------------


def on_pre_build(config: MkDocsConfig, **kwargs: object) -> None:
    """Regenerate the command reference before MkDocs processes pages.

    Skipped if ``extra.generate_commands`` is set to ``false`` in
    ``mkdocs.yml``.
    """
    # Allow opting out via mkdocs.yml config
    if not config.get("extra", {}).get("generate_commands", True):
        log.debug("Command reference generation disabled via extra.generate_commands")
        return

    if not _GENERATOR_SCRIPT.exists():
        log.warning(
            "Generator script not found at %s — skipping command reference generation",
            _GENERATOR_SCRIPT,
        )
        return

    try:
        generator = _load_generator()
        if not hasattr(generator, "_generate"):
            log.warning(
                "Generator module has no _generate() function — skipping. "
                "Was scripts/generate_command_reference.py refactored?",
            )
            return
        content: str = generator._generate()  # type: ignore[attr-defined]
    except Exception:
        log.exception("Failed to generate command reference — skipping")
        return

    # Only write if content changed (avoids unnecessary live-reload triggers)
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if _OUTPUT.exists():
        existing = _OUTPUT.read_text(encoding="utf-8")
        if existing == content:
            log.info("Command reference is up to date — no write needed")
            return

    _OUTPUT.write_text(content, encoding="utf-8")
    log.info("Regenerated %s", _OUTPUT.relative_to(_ROOT))
