# =============================================================================
# Feature Request Issue Template
# =============================================================================
# This template collects information needed to evaluate and implement new
# features. Sections: Introduction, Redirect Notice, Problem & Motivation,
# Proposed Solution, Alternatives, Scope & Impact, Additional Context,
# Contribution Interest, Checklist
# =============================================================================

name: ✨ Feature Request
description: >
  Suggest a new feature or enhancement for the project.
  For early-stage ideas or discussions, please use Discussions first.
title: "[FEATURE] Short description of the feature"
labels: ["enhancement"]
assignees: []

body:
  # ---------------------------------------------------------------------------
  # Introduction
  # ---------------------------------------------------------------------------
  # Brief guidance for the reporter on how to submit a helpful feature request.
  # ---------------------------------------------------------------------------
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! ✨

        A good feature request explains the **problem** you're facing and how
        your proposed solution would help. The more context you provide, the
        easier it is to evaluate and prioritize.

  # ---------------------------------------------------------------------------
  # Redirect Notice
  # ---------------------------------------------------------------------------
  # Encourages users to use Discussions for early-stage ideas before filing a
  # formal feature request.
  # ---------------------------------------------------------------------------
  - type: markdown
    attributes:
      value: |
        ⚠️ **Before submitting**
        - For early-stage ideas or brainstorming, please use [Discussions](https://github.com/JoJo275/simple-python-boilerplate/discussions/categories/ideas) first.
        - Search existing issues and discussions to avoid duplicates.
        - Feature requests should describe a clear, actionable enhancement.

  # ---------------------------------------------------------------------------
  # Problem & Motivation
  # ---------------------------------------------------------------------------
  # Understanding the underlying problem helps evaluate whether this feature
  # is the right solution.
  # ---------------------------------------------------------------------------
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: >
        What problem does this feature solve? Describe the pain point, limitation,
        or frustration you're experiencing.
      placeholder: |
        Example: "I'm always frustrated when..."
        Example: "Currently there's no way to..."
    validations:
      required: true

  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      description: What kind of feature is this?
      options:
        - New feature
        - Enhancement to existing feature
        - Developer experience / tooling
        - Documentation improvement
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: request_type_other
    attributes:
      label: Request Type – Other (if applicable)
      description: >
        If you selected "Other" above, please describe the type of request.
      placeholder: Describe the request type if "Other" was selected.
    validations:
      required: false

  # ---------------------------------------------------------------------------
  # Proposed Solution
  # ---------------------------------------------------------------------------
  # The user's suggested approach to solving the problem.
  # ---------------------------------------------------------------------------
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: >
        Describe the feature you'd like to see. Be as specific as possible about
        the expected behavior, API, or user experience.
      placeholder: |
        Example: "Add a `--verbose` flag that..."
        Example: "A new method `do_thing()` that returns..."
    validations:
      required: true

  - type: textarea
    id: example_usage
    attributes:
      label: Example Usage (Optional)
      description: >
        If applicable, show how the feature would be used in practice.
        Code snippets, CLI examples, or configuration samples are helpful.
      placeholder: |
        from simple_python_boilerplate import new_feature

        # Example showing how the feature would work
        result = new_feature.do_something()
      render: python
    validations:
      required: false

  # ---------------------------------------------------------------------------
  # Alternatives
  # ---------------------------------------------------------------------------
  # Other approaches considered or current workarounds.
  # ---------------------------------------------------------------------------
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: >
        What other solutions have you considered? Are there workarounds you're
        currently using?
      placeholder: |
        Example: "I tried using X, but it doesn't work because..."
        Example: "An alternative would be to..., but that has drawbacks..."
    validations:
      required: false

  # ---------------------------------------------------------------------------
  # Scope & Impact
  # ---------------------------------------------------------------------------
  # Helps prioritize the feature based on its potential impact and scope.
  # ---------------------------------------------------------------------------
  - type: markdown
    attributes:
      value: |
        ## Scope & Impact

        Help us understand the priority and scope of this request.

  - type: dropdown
    id: importance
    attributes:
      label: Importance to You
      description: How important is this feature for your use case?
      options:
        - Critical – Blocking my work
        - High – Significant improvement to my workflow
        - Medium – Nice to have
        - Low – Minor convenience
        - Unsure
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      description: How large do you think this change would be?
      options:
        - Small – Minor change, limited impact
        - Medium – Moderate change, some components affected
        - Large – Significant change, multiple components affected
        - Unsure
    validations:
      required: true

  - type: checkboxes
    id: breaking_change
    attributes:
      label: Breaking Change?
      description: Would this feature require breaking changes to existing functionality?
      options:
        - label: This may introduce breaking changes
          required: false

  # ---------------------------------------------------------------------------
  # Additional Context
  # ---------------------------------------------------------------------------
  # Supporting materials, references, or related issues.
  # ---------------------------------------------------------------------------
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: >
        Add any other context, mockups, screenshots, links to similar features
        in other projects, or related issues/discussions.
      placeholder: |
        - Related issue: #123
        - Similar feature in project X: [link]
        - Mockup attached below
    validations:
      required: false

  # ---------------------------------------------------------------------------
  # Contribution Interest
  # ---------------------------------------------------------------------------
  # Understanding willingness to contribute helps with planning.
  # ---------------------------------------------------------------------------
  - type: dropdown
    id: contribution
    attributes:
      label: Would you be willing to contribute this feature?
      description: >
        Let us know if you're interested in implementing this yourself.
        We're happy to provide guidance!
      options:
        - Yes, I'd like to work on this
        - Yes, but I'd need guidance
        - Maybe, depending on complexity
        - No, I'm just suggesting the idea
    validations:
      required: true

  # ---------------------------------------------------------------------------
  # Checklist
  # ---------------------------------------------------------------------------
  # Final confirmation that the reporter has done due diligence before
  # submitting.
  # ---------------------------------------------------------------------------
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This is a single, focused feature request (not multiple requests)
          required: true
        - label: I have provided enough context to evaluate this request
          required: false
