# ──────────────────────────────────────────────────────────────
# Changelog Workflow
# ──────────────────────────────────────────────────────────────
# ⚠️  NOT USED IN THE DEFAULT CONFIGURATION.
#
# This repo uses release-please for changelog generation (see
# release-please.yml), which bundles CHANGELOG updates inside
# the Release PR automatically.
#
# This file is included as an OPTIONAL ALTERNATIVE for template
# users who prefer git-cliff's standalone changelog generation.
# To use it, enable the repository guard below and remove (or
# disable) the changelog section of release-please if desired.
# ──────────────────────────────────────────────────────────────
#
# Auto-generates a changelog from conventional commit messages
# and opens a PR with the updated CHANGELOG.md.
#
# Uses git-cliff, which reads commit history and groups entries
# by type (feat, fix, docs, etc.) based on conventional commits.
#
# Triggers:
#   - Push to main (regenerate changelog after merges)
#   - Manual dispatch via the GitHub Actions UI
#
# TODO (template users):
#   1. Enable the repository guard (pick ONE):
#        Option A – Replace 'YOURNAME/YOURTEMPLATE' below with
#                   your actual repo slug (e.g. 'myorg/myproject').
#        Option B – Set a repository variable (no YAML edits needed):
#                     vars.ENABLE_CHANGELOG = 'true'
#                   (Settings → Secrets and variables → Actions → Variables)
#   2. (Optional) Add a cliff.toml config file to customize
#      changelog format. Without one, git-cliff uses defaults.
#      See: https://git-cliff.org/docs/configuration
# ──────────────────────────────────────────────────────────────

name: Changelog

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog

    # ── Repository guard ──────────────────────────────────────
    # Prevents this workflow from running on forks or clones
    # that haven't opted in.
    #
    #   Option A  – Edit the hardcoded slug below.
    #   Option B  – Set vars.ENABLE_CHANGELOG = 'true'.
    if: >-
      ${{
        github.repository == 'YOURNAME/YOURTEMPLATE'
        || vars.ENABLE_CHANGELOG == 'true'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Checkout a Git repository at a particular version (v6.0.2)
        with:
          fetch-depth: 0  # Full history needed to generate changelog
          persist-credentials: false

      # Generate (or update) CHANGELOG.md from conventional commits.
      # git-cliff groups commits by type: feat, fix, docs, refactor, etc.
      - name: Generate changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # Generate changelog based on your Git history (v4.7.0)
        with:
          config: cliff.toml  # Optional config; remove if using defaults
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Open a PR with the updated CHANGELOG.md so it can be
      # reviewed before merging. If a PR already exists, it will
      # be updated instead of creating a duplicate.
      - name: Create changelog PR
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # Creates a pull request for changes to your… (v8.1.0)
        with:
          title: "docs: update CHANGELOG.md"
          commit-message: "docs: update CHANGELOG.md"
          branch: changelog/update
          body: |
            Auto-generated changelog update from conventional commits.
            Created by the Changelog workflow.
          labels: documentation
