"""Shared utilities for doctor-family scripts.

Provides low-level helpers used by ``doctor.py``, ``env_doctor.py``,
``git_doctor.py``, and other diagnostic scripts.  Centralises command
execution, package introspection, path checks, TOML parsing, and
pre-commit hook detection so each script doesn't re-implement the
same patterns.

Usage::

    from _doctor_common import get_version, get_package_version, read_pyproject

    version = get_version(["ruff", "--version"])
    pkg = get_package_version("simple-python-boilerplate")
    pyproject = read_pyproject(root)

.. note::
    This is a shared internal module (prefixed with ``_``).  It is excluded
    from the command reference generator and is not intended as a standalone
    CLI.  See ADR 031 for script conventions.
"""

from __future__ import annotations

import importlib.metadata
import re
import shutil
import subprocess  # nosec B404
from pathlib import Path

# TODO (template users): remove try/except once requires-python >= 3.11 is guaranteed
try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]

__all__ = [
    "HOOK_STAGES",
    "check_hook_installed",
    "check_path_exists",
    "extract_repo_slug",
    "get_package_version",
    "get_version",
    "parse_version_specifier",
    "read_pyproject",
]

SCRIPT_VERSION = "1.0.0"

# Pre-commit hook stages that this project expects installed.
HOOK_STAGES = ("pre-commit", "commit-msg", "pre-push")

# TODO (template users): If your project adds custom git hook stages
#   (e.g. post-merge, post-checkout), add them to HOOK_STAGES above
#   so doctor scripts can verify they're installed.


# ---------------------------------------------------------------------------
# Command execution
# ---------------------------------------------------------------------------


def get_version(cmd: list[str], *, timeout: int = 10) -> str:
    """Run a command and extract its first line of output.

    Handles both PATH-based lookups (``["ruff", "--version"]``) and
    absolute-path commands (``[sys.executable, "-m", "pip", ...]``).

    Args:
        cmd: Command and arguments to run.
        timeout: Maximum seconds to wait for the command.

    Returns:
        First line of stdout (or stderr), ``"not found"`` if the
        executable doesn't exist, or ``"error"`` on failure/timeout.
    """
    first = cmd[0]
    # If it's already an absolute path that exists, use it directly;
    # otherwise look it up on PATH via shutil.which.
    if Path(first).is_absolute() and Path(first).exists():
        exe: str = first
    else:
        found = shutil.which(first)
        if not found:
            return "not found"
        exe = found
    try:
        result = subprocess.run(  # nosec B603
            [exe, *cmd[1:]],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return (
            result.stdout.strip().split("\n")[0] or result.stderr.strip().split("\n")[0]
        )
    except (subprocess.TimeoutExpired, OSError):
        return "error"


# ---------------------------------------------------------------------------
# Package introspection
# ---------------------------------------------------------------------------


def get_package_version(package: str) -> str:
    """Get installed package version.

    Args:
        package: Distribution name (e.g. ``"simple-python-boilerplate"``).

    Returns:
        Version string, or ``"not installed"`` if the package isn't found.
    """
    try:
        return importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        return "not installed"


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def check_path_exists(path: Path) -> str:
    """Check if a path exists and report its type.

    Args:
        path: Filesystem path to check.

    Returns:
        ``"directory"``, ``"file"``, or ``"missing"``.
    """
    if not path.exists():
        return "missing"
    if path.is_dir():
        return "directory"
    return "file"


# ---------------------------------------------------------------------------
# Pre-commit hook detection
# ---------------------------------------------------------------------------


def check_hook_installed(hook_path: Path) -> str:
    """Check if a git hook file is a real pre-commit hook (not a sample).

    Reads the hook file content to distinguish between a pre-commit
    managed hook, a Git sample, a custom script, or a missing file.

    Detection looks for the marker that ``pre-commit install`` writes
    into generated hooks (e.g. ``"File generated by pre-commit"``).

    Args:
        hook_path: Path to the hook file
            (e.g. ``root / ".git" / "hooks" / "pre-commit"``).

    Returns:
        ``"installed"`` if managed by pre-commit, ``"sample"`` if it's
        a Git sample hook, ``"custom"`` for other scripts, or
        ``"missing"`` if absent.
    """
    if not hook_path.is_file():
        return "missing"
    try:
        content = hook_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return "missing"
    # pre-commit install writes "File generated by pre-commit" or
    # "Generated by pre-commit" into the hook shim.
    if "generated by pre-commit" in content.lower():
        return "installed"
    if "This sample" in content or ".sample" in hook_path.name:
        return "sample"
    return "custom"


# ---------------------------------------------------------------------------
# TOML / pyproject helpers
# ---------------------------------------------------------------------------


def read_pyproject(root: Path) -> dict[str, object] | None:
    """Read and parse ``pyproject.toml``, returning ``None`` on failure.

    Args:
        root: Repository root directory.

    Returns:
        Parsed TOML dict, or ``None`` if the file is missing or unparsable.
    """
    if tomllib is None:
        return None
    path = root / "pyproject.toml"
    if not path.is_file():
        return None
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def parse_version_specifier(spec: str) -> str:
    """Extract a normalized package name from a PEP 508 dependency string.

    Args:
        spec: A dependency string like ``"pytest>=8.0"`` or ``"ruff>=0.11"``.

    Returns:
        Normalized package name (lowercase, hyphens → underscores).
    """
    match = re.match(r"^([A-Za-z0-9][-A-Za-z0-9_.]*)", spec.strip())
    return match.group(1).lower().replace("-", "_") if match else spec.strip().lower()


def extract_repo_slug(url: str) -> str:
    """Extract ``owner/repo`` from a GitHub URL.

    Args:
        url: Git remote URL (HTTPS or SSH).

    Returns:
        ``"owner/repo"`` string, or empty string if not a GitHub URL.
    """
    match = re.search(r"github\.com[:/]([^/]+/[^/.]+)", url)
    return match.group(1) if match else ""
